---
- hosts: all
  roles:
    - { role: chrome,      tags: "desktop,chrome" }
    - { role: sublimetext, tags: "desktop,sublimetext" }
    - { role: spotify,     tags: "desktop,spotify" }

    - { role: virtualbox, tags: "virtual" }
    - { role: vagrant,    tags: "virtual" }
