---
- hosts: all
  roles:
    - { role: chrome,      tags: "desktop" }
    - { role: sublimetext, tags: "desktop" }

    - { role: virtualbox, tags: "virtual" }
    - { role: vagrant,    tags: "virtual" }
