---
- hosts: all
  connection: local
  become: true
  become_user: root
  gather_facts: no
  roles:
    - { role: chrome,      tags: "desktop,chrome" }
    - { role: sublimetext, tags: "desktop,sublimetext" }
    - { role: spotify,     tags: "desktop,spotify" }

    # broken if using beta relase of ubuntu :0(
    #- { role: virtualbox, tags: "virtual" }
    #- { role: vagrant,    tags: "virtual" }

    - { role: terraform,   tags: "terraform" }

# TBD:
# zoom (webinars) ; reqs libxcb-xtest0
