---
- name: Does the Spotify apt file exist?
  command: test -f {{apt_file}}
  register: apt_exists
  ignore_errors: True

- name: Add Spotify key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2C19886
  when: apt_exists.rc == 1

- name: Add Spotify repo
  copy: content="deb http://repository.spotify.com stable non-free" dest={{apt_file}} owner=root group=root mode=644
  when: apt_exists.rc == 1

- name: Update apt cache
  apt: update_cache=yes
  when: apt_exists.rc == 1

- name: Install Spotify
  apt: pkg=spotify-client state=installed
