---

##########
# Spotify on Unbutu 15.04 misses libgcrypt11 dependancy

- name: Is package installed?
  shell: dpkg -l {{ deb_pkg_short }} | tail -1 | cut -c1-2
  register: dpkg_status    # should be "ii" if already installed

- name: Install package
  package:
    name: "{{ deb_pkg_short }}"
    state: present
  when: "'ii' not in dpkg_status.stdout"

##########
- name: Does the Spotify apt file exist?
  command: test -f {{apt_file}}
  register: apt_exists
  ignore_errors: True

- name: Add Spotify repo key
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2C19886
  when: apt_exists.rc == 1

- name: Add Spotify repo
  copy: content="deb http://repository.spotify.com stable non-free" dest={{apt_file}} owner=root group=root mode=644
  when: apt_exists.rc == 1

- name: Update apt cache
  apt: update_cache=yes
  when: apt_exists.rc == 1

- name: Install Spotify
  apt: pkg=spotify-client state=installed
