---
deb_pkg_short: vagrant
vagrant_version: "1.7.4"
deb_pkg_long: "{{ deb_pkg_short }}_{{ vagrant_version }}_x86_64.deb"
deb_pkg_url: https://dl.bintray.com/mitchellh/{{ deb_pkg_short }}/{{ deb_pkg_long }}
deb_pkg_cksum: sha256:050411ba8b36e322c4ce32990d2539e73a87fabd932f7397d2621986084eda6a

