---
- name: Does the Oracle VirtualBox apt file exist?
  command: test -f {{apt_file}}
  register: apt_exists
  ignore_errors: True

- name: Add Oracle VBox key
  shell: wget -q -O - https://www.virtualbox.org/download/oracle_vbox.asc   | apt-key add -
  when: apt_exists.rc == 1

- name: Add Oracle VBox repo
  copy: content="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" dest={{apt_file}} owner=root group=root mode=644
  when: apt_exists.rc == 1

- name: Update apt cache
  apt: update_cache=yes
  when: apt_exists.rc == 1

- name: Install Oracle VirtualBox
  apt: pkg=virtualbox-5.0 state=installed

